### ISSUE TITLE
Can't get this to compile with current setup

### ISSUE THREAD

**Issue by kellyjandrews** [jmptable/l3d-library#1]
I've been trying to get this code set to work - but currently unable to get things to compile. 

Currently getting this back:

``` bash
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../modules/photon/user-part
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../../user
build.mk:37: *** "No sources found in ./applications/streaming".  Stop.
make[1]: *** [user] Error 2
make: *** [modules/photon/user-part] Error 2
```

I've attempted to move files around and get it to build successfully - but no luck.  Is there somewhere else I should be looking?

**Comment by jmpinit** [comment]
Unfortunately the library has not been kept up to date with the changes that Spark / Particle has made to their firmware, so to build it you need to use a version from more than about 3 months ago or make changes to get the build to be compatible with the current Spark Core firmware.

**Comment by kellyjandrews** [comment]
Thanks - just making sure I wasn't doing anything dumb.  Thanks for the follow up!
